# Generated by Django 4.0.4 on 2022-07-08 14:12

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.CharField(max_length=50, verbose_name='url')),
                ('description', models.CharField(max_length=500, verbose_name='desciption')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='main.category', verbose_name='دسته اصلی')),
            ],
            options={
                'verbose_name': 'category ',
                'verbose_name_plural': 'categorys',
            },
        ),
        migrations.CreateModel(
            name='NewsLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null='False', verbose_name='title')),
                ('slug', models.SlugField(null='False', verbose_name='url')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank='True', null='True')),
                ('thumbnail', models.ImageField(null='True', upload_to='images', verbose_name='picture-url')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('p', 'blog'), (' d ', 'DRAFT'), ('x', 'slider'), ('y', 'پین کردن')], max_length=3, null='False', verbose_name='status')),
                ('auther', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='auther')),
                ('category', models.ManyToManyField(related_name='articles', to='main.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Main ',
                'verbose_name_plural': 'Mains',
            },
        ),
    ]
