# Generated by Django 4.0.4 on 2022-07-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mainmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmodel',
            name='status',
            field=models.CharField(choices=[('p', 'blog'), (' d ', 'DRAFT'), ('x', 'slider')], max_length=3, null='False', verbose_name='status'),
        ),
    ]
