# Generated by Django 4.0.4 on 2022-07-26 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mainmodel_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان ')),
                ('description', models.TextField(max_length=100, verbose_name='توضیحات')),
                ('slug', models.SlugField(verbose_name='آدرس')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار ')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت ')),
            ],
        ),
        migrations.RemoveField(
            model_name='mainmodel',
            name='hits',
        ),
        migrations.AddField(
            model_name='mainmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='main.tag', verbose_name=' برچسب'),
        ),
    ]
