# Generated by Django 4.0.4 on 2023-02-22 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.mainmodel'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
