# Generated by Django 4.1.7 on 2023-03-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_commentmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
